# Generated by Django 2.2.16 on 2020-11-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=20)),
                ('full_address', models.CharField(max_length=500)),
                ('province', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=100)),
                ('old_district', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'restuarant',
            },
        ),
        migrations.CreateModel(
            name='SubwaysNearRestaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subways_near_restaurants', to='restaurants.Restaurants')),
                ('subway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subways_near_restaurants', to='subways.Subway')),
            ],
            options={
                'db_table': 'subways_near_restaurants',
            },
        ),
        migrations.AddField(
            model_name='restaurants',
            name='subway',
            field=models.ManyToManyField(related_name='restaurants', through='restaurants.SubwaysNearRestaurants', to='subways.Subway'),
        ),
    ]
