# Generated by Django 2.2.16 on 2020-11-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='old_district',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
