# Generated by Django 2.2.16 on 2020-10-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='province',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='lng',
            field=models.DecimalField(decimal_places=7, max_digits=20),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
