# Generated by Django 2.2.16 on 2020-11-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_restaurants_old_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='full_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='old_district',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='province',
            field=models.CharField(max_length=20),
        ),
    ]
