# Generated by Django 2.2.16 on 2020-10-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20201018_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='full_address',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
