# Generated by Django 2.2.16 on 2023-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20220410_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='naver_map_place_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
