# Generated by Django 2.2.16 on 2020-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('categoryCode', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainFoodCategory',
            fields=[
                ('foodcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foods.FoodCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('foods.foodcategory',),
        ),
        migrations.CreateModel(
            name='SubFoodCategory',
            fields=[
                ('foodcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='foods.FoodCategory')),
            ],
            options={
                'abstract': False,
            },
            bases=('foods.foodcategory',),
        ),
    ]
