# Generated by Django 2.2.16 on 2020-10-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainfoodcategory',
            name='categoryCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subfoodcategory',
            name='categoryCode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
