# Generated by Django 2.2.16 on 2020-10-18 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('foods', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('embeddable', models.BooleanField(default=False)),
                ('youtube_video_thumbnail', models.TextField(blank=True, max_length=500)),
                ('youtube_video_tags', models.TextField(blank=True, max_length=1000)),
                ('youtube_video_duration', models.TimeField(blank=True)),
                ('youtube_video_start_time', models.IntegerField(default=0)),
                ('youtube_video_published_at', models.DateTimeField(blank=True)),
                ('is_advertising', models.BooleanField(default=False)),
                ('youtube_video_original_title', models.CharField(max_length=300)),
                ('youtube_video_korean_title', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube_video_english_title', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube_video_japanese_title', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube_video_chinese_title', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube_video_vietnamese_title', models.CharField(blank=True, max_length=300, null=True)),
                ('youtube_video_original_desc', models.TextField(max_length=1000)),
                ('youtube_video_korean_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('youtube_video_english_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('youtube_video_japanese_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('youtube_video_chinese_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('youtube_video_vietnamese_desc', models.TextField(blank=True, max_length=1000, null=True)),
                ('youtube_video_korean_caption', models.IntegerField(blank=True, null=True)),
                ('youtube_video_english_caption', models.IntegerField(blank=True, null=True)),
                ('youtube_video_japanese_caption', models.IntegerField(blank=True, null=True)),
                ('youtube_video_chinese_caption', models.IntegerField(blank=True, null=True)),
                ('youtube_video_vietnamese_caption', models.IntegerField(blank=True, null=True)),
                ('MainFoodCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='foods.MainFoodCategory')),
                ('Restaurants', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='restaurants.Restaurants')),
            ],
            options={
                'db_table': 'youtube_video',
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideoSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('sub_food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.SubFoodCategory')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.YoutubeVideo')),
            ],
            options={
                'db_table': 'youtube_video_sub_category',
            },
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='SubFoodCategory',
            field=models.ManyToManyField(related_name='youtube_videos', through='videos.YoutubeVideoSubCategory', to='foods.SubFoodCategory'),
        ),
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='users.YoutubeChannel'),
        ),
    ]
