# Generated by Django 2.2.16 on 2020-10-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('users', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('youtube_video_id', models.CharField(max_length=100)),
                ('embeddable', models.BooleanField(default=False)),
                ('video_link', models.CharField(max_length=300)),
                ('video_thumbnail', models.TextField(max_length=500)),
                ('video_tags', models.TextField(max_length=1000)),
                ('video_youtube_category_id', models.IntegerField()),
                ('video_duration', models.TimeField()),
                ('video_start_time', models.TimeField()),
                ('video_published_at', models.DateTimeField()),
                ('is_advertising', models.BooleanField(default=False)),
                ('video_original_title', models.CharField(max_length=300)),
                ('video_korean_title', models.CharField(max_length=300, null=True)),
                ('video_english_title', models.CharField(max_length=300, null=True)),
                ('video_japanese_title', models.CharField(max_length=300, null=True)),
                ('video_chinese_title', models.CharField(max_length=300, null=True)),
                ('video_vietnamese_title', models.CharField(max_length=300, null=True)),
                ('video_original_desc', models.TextField(max_length=1000)),
                ('video_korean_desc', models.TextField(max_length=1000, null=True)),
                ('video_english_desc', models.TextField(max_length=1000, null=True)),
                ('video_japanese_desc', models.TextField(max_length=1000, null=True)),
                ('video_chinese_desc', models.TextField(max_length=1000, null=True)),
                ('video_vietnamese_desc', models.TextField(max_length=1000, null=True)),
                ('video_korean_caption', models.IntegerField(blank=True, null=True)),
                ('video_english_caption', models.IntegerField(blank=True, null=True)),
                ('video_japanese_caption', models.IntegerField(blank=True, null=True)),
                ('video_chinese_caption', models.IntegerField(blank=True, null=True)),
                ('video_vietnamese_caption', models.IntegerField(blank=True, null=True)),
                ('MainFoodCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='foods.MainFoodCategory')),
                ('Restaurants', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='restaurants.Restaurants')),
                ('SubFoodCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='foods.SubFoodCategory')),
                ('youtube_channel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='users.YoutubeChannel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
