# Generated by Django 2.2.16 on 2020-11-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='embeddable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_chinese_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_chinese_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_english_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_english_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_japanese_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_japanese_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_korean_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_korean_title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_original_desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_original_title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_start_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_tags',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_thumbnail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_vietnamese_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_vietnamese_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
