# Generated by Django 2.2.16 on 2020-11-17 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20201117_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='main_food_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='foods.MainFoodCategory'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='restaurants.Restaurants'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='channels.YoutubeChannel'),
        ),
    ]
