# Generated by Django 2.2.16 on 2020-11-17 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20201117_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_original_desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
