# Generated by Django 2.2.16 on 2020-10-18 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_youtubevideo_youtube_video_memos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='MainFoodCategory',
            new_name='food_main_category',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='SubFoodCategory',
            new_name='food_sub_category',
        ),
        migrations.RenameField(
            model_name='youtubevideo',
            old_name='Restaurants',
            new_name='restaurant',
        ),
    ]
