# Generated by Django 2.2.16 on 2023-07-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20220410_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='embeddable',
            field=models.BooleanField(null=True),
        ),
    ]
