# Generated by Django 2.2.16 on 2020-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_auto_20201018_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
