# Generated by Django 2.2.16 on 2020-10-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20201018_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_videos', to='channels.YoutubeChannel'),
        ),
    ]
