# Generated by Django 2.2.16 on 2023-07-16 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20230715_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='embeddable',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_published_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_start_time',
            field=models.IntegerField(),
        ),
    ]
