# Generated by Django 2.2.16 on 2023-07-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20230716_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='embeddable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
