# Generated by Django 2.2.16 on 2020-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20201022_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_original_desc',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='youtube_video_original_title',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
