# Generated by Django 2.2.16 on 2020-11-10 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20201108_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideo',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='youtube_videos', to='restaurants.Restaurants'),
        ),
    ]
