# Generated by Django 2.2.16 on 2023-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_auto_20230716_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='youtube_episode_num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
