# Generated by Django 2.2.16 on 2020-11-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
        migrations.DeleteModel(
            name='UserFavoriteRestaurant',
        ),
    ]
