# Generated by Django 2.2.16 on 2020-10-22 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20201022_1246'),
        ('users', '0002_auto_20201018_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='subscribe',
            field=models.ManyToManyField(related_name='users', through='users.UserSubscribeChannel', to='channels.YoutubeChannel'),
        ),
        migrations.AlterField(
            model_name='usersubscribechannel',
            name='youtube_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.YoutubeChannel'),
        ),
        migrations.DeleteModel(
            name='YoutubeChannel',
        ),
    ]
