# Generated by Django 2.2.16 on 2020-11-15 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
        ('users', '0002_auto_20201115_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteRestaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_videos', to='restaurants.Restaurants')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite',
            field=models.ManyToManyField(related_name='users', through='users.UserFavoriteRestaurant', to='restaurants.Restaurants'),
        ),
    ]
