# Generated by Django 2.2.16 on 2020-10-18 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201017_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubechannel',
            name='channel_address',
        ),
        migrations.RemoveField(
            model_name='youtubechannel',
            name='channel_profile_img',
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='channel_keyword',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='youtubechannel',
            name='channel_thumbnail',
            field=models.TextField(blank=True),
        ),
    ]
