# Generated by Django 2.2.16 on 2020-11-08 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201108_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfavoritevideo',
            name='youtube_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_favorite_videos', to='videos.YoutubeVideo'),
        ),
        migrations.AlterField(
            model_name='usersubscribechannel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribe_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersubscribechannel',
            name='youtube_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_subscribe_channels', to='channels.YoutubeChannel'),
        ),
    ]
