# Generated by Django 2.2.16 on 2020-11-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSearchLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('search_keyword', models.CharField(max_length=200)),
                ('food_keyword', models.TextField(blank=True, null=True)),
                ('region_keyword', models.TextField(blank=True, null=True)),
                ('channel_keyword', models.TextField(blank=True, null=True)),
                ('subway_keyword', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_search_logs', to='devices.Device')),
            ],
            options={
                'db_table': 'device_search_log',
            },
        ),
        migrations.CreateModel(
            name='DeviceClickLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_click_logs', to='devices.Device')),
                ('youtube_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_click_logs', to='videos.YoutubeVideo')),
            ],
            options={
                'db_table': 'device_click_log',
            },
        ),
    ]
