# Generated by Django 2.2.16 on 2020-10-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deviceclicklog',
            old_name='user',
            new_name='device',
        ),
    ]
