# Generated by Django 2.2.16 on 2022-04-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20220413_1326'),
        ('restaurants', '0002_auto_20220410_1430'),
        ('logs', '0002_auto_20220410_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFavoriteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('favorite_click', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_favorite_logs', to='devices.Device')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_favorite_logs', to='restaurants.Restaurants')),
            ],
            options={
                'db_table': 'device_favorite_log',
            },
        ),
    ]
