# Generated by Django 2.2.16 on 2020-11-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_auto_20201029_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesearchlog',
            name='channel_keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesearchlog',
            name='food_keyword',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicesearchlog',
            name='region_keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
