# Generated by Django 2.2.16 on 2020-11-10 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20201101_0446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceclicklog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_click_logs', to='devices.Device'),
        ),
        migrations.AlterField(
            model_name='devicesearchlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='device_search_logs', to='devices.Device'),
        ),
    ]
