# Generated by Django 2.2.16 on 2020-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_auto_20201110_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesearchlog',
            name='subway_keyword',
            field=models.TextField(blank=True, null=True),
        ),
    ]
