# Generated by Django 2.2.16 on 2020-11-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_thumbnail', models.TextField()),
                ('channel_id', models.CharField(max_length=100)),
                ('channel_desc', models.TextField(blank=True, max_length=10000)),
                ('channel_keyword', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('none_request', 'None request'), ('want_sign_up', 'Want sign up'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='none_request', max_length=30)),
            ],
            options={
                'db_table': 'youtube_channel',
            },
        ),
    ]
