# Generated by Django 2.2.16 on 2020-11-08 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_desc',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
