# Generated by Django 2.2.16 on 2020-11-17 14:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_youtubechannel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannel',
            name='channel_country',
            field=django_countries.fields.CountryField(default='KR', max_length=2),
        ),
    ]
