# Generated by Django 2.2.16 on 2020-11-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_auto_20201108_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='channel_thumbnail',
            field=models.TextField(),
        ),
    ]
