# Generated by Django 2.2.16 on 2022-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_auto_20201117_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubechannel',
            name='deleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
