# Generated by Django 2.2.16 on 2022-04-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('application_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Application kinds',
                'db_table': 'application_kind',
            },
        ),
        migrations.CreateModel(
            name='ApplicationPlatform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('platform_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Application platforms',
                'db_table': 'application_platform',
            },
        ),
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('curr_app_version', models.CharField(blank=True, max_length=50)),
                ('min_app_version', models.CharField(blank=True, max_length=50)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_config', to='apps.ApplicationPlatform')),
            ],
            options={
                'verbose_name_plural': 'Application version configs',
                'db_table': 'app_version_config',
            },
        ),
    ]
