# Generated by Django 2.2.16 on 2022-04-15 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationkind',
            name='channel',
        ),
    ]
