# Generated by Django 2.2.16 on 2022-04-10 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_applicationconfig_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationconfig',
            name='application_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_config', to='apps.ApplicationKind'),
        ),
    ]
