# Generated by Django 2.2.16 on 2022-04-15 15:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_auto_20220410_1430'),
        ('apps', '0002_remove_applicationkind_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationkind',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='application_kind', to='channels.YoutubeChannel'),
            preserve_default=False,
        ),
    ]
