# Generated by Django 2.2.16 on 2023-07-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_applicationkind_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationconfig',
            name='version',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
