# Generated by Django 2.2.16 on 2022-04-10 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20220410_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationconfig',
            old_name='application_name',
            new_name='application',
        ),
    ]
