# Generated by Django 2.2.16 on 2023-07-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_applicationconfig_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationconfig',
            old_name='version',
            new_name='data_version',
        ),
    ]
